# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Documentation
    pre: "<script id='docscript' language='javascript'>var el = document.getElementById('docscript'); while(el.nodeName != 'A') { el = el.parentElement; } el.target = '';</script><i class='fa fa-book pr-1'></i>"
    url: 'https://doc.ccf-testing.org'
    weight: 10

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
