[build]
command = """
hugo --gc --minify --enableGitInfo -b $URL
"""
publish = "public"

[build.environment]
HUGO_VERSION = "0.95.0"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = """
hugo --gc --minify --enableGitInfo --buildFuture -b $DEPLOY_PRIME_URL
"""

[context.branch-deploy]
command = """
hugo --gc --minify --enableGitInfo -b $DEPLOY_PRIME_URL
"""

[[plugins]]
package = "netlify-plugin-hugo-cache-resources"
[plugins.inputs]
debug = true
